export const ukraineLanguage = {
    logoLogin: 'Безпечна доставка вантажів | УВІЙТИ',
    notRegistered: 'Не зареєстровані?',
    contactManager: 'Зверніться до свого менеджера',
    signIn: 'УВІЙТИ',
    changeStatus: 'Змінити статус',
    shipping: 'Доставка',
    status: 'Статус',
    dispatchTime: 'Витрачений час',
    arrivalTime: 'Час прибуття',
    registerDate: 'Дата реєстрації',
    send: 'ПОЧАТИ ВІДПРАВЛЕННЯ',
    planned: 'ЗАПЛАНОВАНО',
    deliver: 'ДОСТАВИТИ',
    delivered: 'ДОСТАВЛЕНО',
    profile: 'ПРОФІЛЬ',
    logout: 'ВИЙТИ',
    changeLanguage: 'Змінити мову',
    noDataFound: 'Даних не знайдено',
    name: `Ім'я`,
    surname: 'Прізвище',
    email: 'Email',
    nameMustBeFilled: `Ім'я має бути заповнене`,
    surnameMustBeFilled: 'Прізвище має бути заповнене'
}
export const englishLanguage = {
    notRegistered: 'Not registered?',
    logoLogin: 'Safe delivery of goods | LOGIN',
    contactManager: 'Contact your manager',
    signIn: 'SIGN IN',
    changeStatus: 'Change status',
    shipping: 'Shipping',
    status: 'Status',
    dispatchTime: 'Dispatch ime',
    arrivalTime: 'Arrival time',
    registerDate: 'Register date',
    send: 'SEND',
    planned: 'PLANNED',
    deliver: 'DELIVER',
    delivered: 'DELIVERED',
    profile: 'PROFILE',
    logout: 'LOGOUT',
    changeLanguage: 'Change Language',
    noDataFound: 'No data found',
    name: 'Name',
    surname: 'Surname',
    email: 'Email',
    nameMustBeFilled: 'Name must be filled',
    surnameMustBeFilled: 'Surname must be filled'

}